/** Extra system modules for landing / full-site / travel packs (Phases 1–3). */
export const EXTRA_SYSTEM_MODULES = [
  // ——— Phase 1 ———
  {
    key: 'logo_cloud',
    name: 'Logo cloud',
    category: 'social_proof',
    rendererKey: 'logo_cloud',
    schemaJson: [
      { key: 'eyebrow', label: 'Eyebrow', type: 'text' },
      { key: 'title', label: 'Title', type: 'text' },
      { key: 'items', label: 'Logos', type: 'list' },
    ],
    defaultPropsJson: {
      eyebrow: 'Trusted by',
      title: 'Partners & brands we work with',
      items: [
        { url: '', alt: 'Partner one', href: '' },
        { url: '', alt: 'Partner two', href: '' },
        { url: '', alt: 'Partner three', href: '' },
        { url: '', alt: 'Partner four', href: '' },
      ],
    },
    previewJson: { summary: 'Partner / client logo grid' },
  },
  {
    key: 'stats',
    name: 'Stats strip',
    category: 'social_proof',
    rendererKey: 'stats',
    schemaJson: [
      { key: 'eyebrow', label: 'Eyebrow', type: 'text' },
      { key: 'title', label: 'Title', type: 'text' },
      { key: 'items', label: 'Stats', type: 'list' },
    ],
    defaultPropsJson: {
      eyebrow: 'By the numbers',
      title: '',
      items: [
        { value: '12+', label: 'Years planning' },
        { value: '400+', label: 'Trips crafted' },
        { value: '98%', label: 'Would recommend' },
        { value: '24h', label: 'Typical reply' },
      ],
    },
    previewJson: { summary: 'Metric / KPI strip' },
  },
  {
    key: 'feature_grid',
    name: 'Feature grid',
    category: 'content',
    rendererKey: 'feature_grid',
    schemaJson: [
      { key: 'eyebrow', label: 'Eyebrow', type: 'text' },
      { key: 'title', label: 'Title', type: 'text' },
      { key: 'body', label: 'Intro', type: 'textarea' },
      {
        key: 'columns',
        label: 'Columns',
        type: 'select',
        options: [
          { value: '2', label: '2' },
          { value: '3', label: '3' },
          { value: '4', label: '4' },
        ],
      },
      { key: 'items', label: 'Features', type: 'list' },
    ],
    defaultPropsJson: {
      eyebrow: 'Why us',
      title: 'Everything you need for a smooth journey',
      body: 'Clear planning, local know-how, and support when it matters.',
      columns: '3',
      items: [
        { icon: '✦', title: 'Local expertise', body: 'On-ground partners who know the places you will love.' },
        { icon: '◈', title: 'Tailored plans', body: 'Itineraries shaped around your pace, budget, and style.' },
        { icon: '◎', title: 'Calm support', body: 'A real team on call before and during your trip.' },
      ],
    },
    previewJson: { summary: 'Icon / title / body feature cards' },
  },
  {
    key: 'feature_split',
    name: 'Feature split',
    category: 'content',
    rendererKey: 'feature_split',
    schemaJson: [
      { key: 'eyebrow', label: 'Eyebrow', type: 'text' },
      { key: 'title', label: 'Title', type: 'text' },
      { key: 'body', label: 'Body', type: 'textarea' },
      { key: 'imageUrl', label: 'Image', type: 'url' },
      { key: 'imageAlt', label: 'Image alt', type: 'text' },
      { key: 'ctaLabel', label: 'CTA label', type: 'text' },
      { key: 'ctaHref', label: 'CTA link', type: 'url' },
      {
        key: 'imageSide',
        label: 'Image side',
        type: 'select',
        options: [
          { value: 'left', label: 'Left' },
          { value: 'right', label: 'Right' },
        ],
      },
    ],
    defaultPropsJson: {
      eyebrow: 'Featured',
      title: 'A stay that feels like home',
      body: 'Thoughtful rooms, quiet corners, and mornings that start slowly.',
      imageUrl: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1200&q=80',
      imageAlt: 'Hotel interior',
      ctaLabel: 'Explore stays',
      ctaHref: '/about',
      imageSide: 'right',
    },
    previewJson: { summary: 'Image + copy split' },
  },
  {
    key: 'pricing',
    name: 'Pricing',
    category: 'conversion',
    rendererKey: 'pricing',
    schemaJson: [
      { key: 'eyebrow', label: 'Eyebrow', type: 'text' },
      { key: 'title', label: 'Title', type: 'text' },
      { key: 'body', label: 'Intro', type: 'textarea' },
      { key: 'items', label: 'Plans', type: 'list' },
    ],
    defaultPropsJson: {
      eyebrow: 'Plans',
      title: 'Simple pricing',
      body: 'Choose a starting point — we will refine it with you.',
      items: [
        {
          name: 'Essentials',
          price: 'From $890',
          features: 'Airport transfer\n3 nights stay\nDaily breakfast',
          ctaLabel: 'Enquire',
          ctaHref: '/contact',
          highlighted: false,
        },
        {
          name: 'Signature',
          price: 'From $1,490',
          features: 'Everything in Essentials\nPrivate guide (1 day)\nWelcome dinner',
          ctaLabel: 'Enquire',
          ctaHref: '/contact',
          highlighted: true,
        },
        {
          name: 'Private',
          price: 'Custom',
          features: 'Fully bespoke itinerary\nDedicated planner\nPriority support',
          ctaLabel: 'Talk to us',
          ctaHref: '/contact',
          highlighted: false,
        },
      ],
    },
    previewJson: { summary: 'Pricing plan cards' },
  },
  {
    key: 'team',
    name: 'Team',
    category: 'content',
    rendererKey: 'team',
    schemaJson: [
      { key: 'eyebrow', label: 'Eyebrow', type: 'text' },
      { key: 'title', label: 'Title', type: 'text' },
      { key: 'body', label: 'Intro', type: 'textarea' },
      { key: 'items', label: 'People', type: 'list' },
    ],
    defaultPropsJson: {
      eyebrow: 'People',
      title: 'Meet the team',
      body: 'The humans behind the journeys.',
      items: [
        {
          photo: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=400&q=80',
          name: 'Maya Chen',
          role: 'Founder',
          bio: 'Fifteen years crafting trips across Asia.',
        },
        {
          photo: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=80',
          name: 'Leo Park',
          role: 'Trip designer',
          bio: 'Obsessed with quiet trails and good food.',
        },
      ],
    },
    previewJson: { summary: 'Team member cards' },
  },
  {
    key: 'logo_header_strip',
    name: 'Announcement bar',
    category: 'content',
    rendererKey: 'logo_header_strip',
    schemaJson: [
      { key: 'text', label: 'Message', type: 'text', required: true },
      { key: 'href', label: 'Link', type: 'url' },
      { key: 'linkLabel', label: 'Link label', type: 'text' },
    ],
    defaultPropsJson: {
      text: 'Early-bird rates for autumn departures — limited seats.',
      href: '/contact',
      linkLabel: 'Enquire now',
    },
    previewJson: { summary: 'Slim promo / announcement bar' },
  },
  {
    key: 'blog_cards',
    name: 'Blog cards',
    category: 'content',
    rendererKey: 'blog_cards',
    schemaJson: [
      { key: 'eyebrow', label: 'Eyebrow', type: 'text' },
      { key: 'title', label: 'Title', type: 'text' },
      { key: 'items', label: 'Articles', type: 'list' },
    ],
    defaultPropsJson: {
      eyebrow: 'Journal',
      title: 'Stories from the road',
      items: [
        {
          image: 'https://images.unsplash.com/photo-1506929562365-f9e4a1d0c5b5?auto=format&fit=crop&w=800&q=80',
          title: 'Three quiet beaches near town',
          excerpt: 'Where to go when you want the sea without the crowds.',
          href: '/about',
        },
        {
          image: 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?auto=format&fit=crop&w=800&q=80',
          title: 'Packing light for monsoon',
          excerpt: 'A short list that still covers sudden weather.',
          href: '/about',
        },
      ],
    },
    previewJson: { summary: 'Article / blog card grid' },
  },
  {
    key: 'contact_block',
    name: 'Contact block',
    category: 'conversion',
    rendererKey: 'contact_block',
    schemaJson: [
      { key: 'eyebrow', label: 'Eyebrow', type: 'text' },
      { key: 'title', label: 'Title', type: 'text' },
      { key: 'address', label: 'Address', type: 'textarea' },
      { key: 'phone', label: 'Phone', type: 'text' },
      { key: 'email', label: 'Email', type: 'text' },
      { key: 'hours', label: 'Hours', type: 'text' },
      { key: 'mapEmbedUrl', label: 'Map embed URL', type: 'url' },
    ],
    defaultPropsJson: {
      eyebrow: 'Visit',
      title: 'Find us',
      address: '12 Harbour Lane\nYour City, 00000',
      phone: '+1 555 0100',
      email: 'hello@example.com',
      hours: 'Mon–Fri 9:00–18:00',
      mapEmbedUrl: '',
    },
    previewJson: { summary: 'Contact details + optional map' },
  },
  {
    key: 'newsletter',
    name: 'Newsletter',
    category: 'conversion',
    rendererKey: 'newsletter',
    schemaJson: [
      { key: 'eyebrow', label: 'Eyebrow', type: 'text' },
      { key: 'title', label: 'Title', type: 'text' },
      { key: 'body', label: 'Body', type: 'textarea' },
      { key: 'placeholder', label: 'Email placeholder', type: 'text' },
      {
        key: 'fieldGap',
        label: 'Label–field gap',
        type: 'select',
        options: [
          { value: '0.35rem', label: 'Tight' },
          { value: '0.75rem', label: 'Normal' },
          { value: '1.25rem', label: 'Relaxed' },
          { value: '1.75rem', label: 'Wide' },
        ],
      },
      { key: 'buttonLabel', label: 'Button label', type: 'text' },
      { key: 'formKey', label: 'Form key', type: 'select' },
    ],
    defaultPropsJson: {
      eyebrow: 'Stay close',
      title: 'Travel notes in your inbox',
      body: 'Occasional ideas, never spam.',
      placeholder: 'you@email.com',
      fieldGap: '0.75rem',
      buttonLabel: 'Subscribe',
      formKey: 'contact',
    },
    previewJson: { summary: 'Email capture band' },
  },
  {
    key: 'divider',
    name: 'Divider',
    category: 'layout',
    rendererKey: 'divider',
    schemaJson: [
      { key: 'height', label: 'Height', type: 'text', helpText: 'e.g. 2rem or 48px' },
      { key: 'showRule', label: 'Show rule', type: 'boolean' },
    ],
    defaultPropsJson: { height: '2.5rem', showRule: true },
    previewJson: { summary: 'Vertical spacer / rule' },
  },
  {
    key: 'embed',
    name: 'Embed',
    category: 'content',
    rendererKey: 'embed',
    schemaJson: [
      { key: 'title', label: 'Title', type: 'text' },
      { key: 'src', label: 'Embed URL', type: 'url', required: true },
      {
        key: 'aspectRatio',
        label: 'Aspect ratio',
        type: 'select',
        options: [
          { value: '16/9', label: '16:9' },
          { value: '4/3', label: '4:3' },
          { value: '1/1', label: '1:1' },
          { value: '21/9', label: '21:9' },
        ],
      },
    ],
    defaultPropsJson: {
      title: '',
      src: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
      aspectRatio: '16/9',
    },
    previewJson: { summary: 'Video / iframe embed' },
  },
  // ——— Phase 2 ———
  {
    key: 'page_header',
    name: 'Page header',
    category: 'content',
    rendererKey: 'page_header',
    schemaJson: [
      { key: 'eyebrow', label: 'Eyebrow', type: 'text' },
      { key: 'title', label: 'Title', type: 'text', required: true },
      { key: 'subhead', label: 'Subhead', type: 'textarea' },
    ],
    defaultPropsJson: {
      eyebrow: 'About',
      title: 'Who we are',
      subhead: 'A short line that sets the tone for this page.',
    },
    previewJson: { summary: 'Inner page title band' },
  },
  {
    key: 'tabs_content',
    name: 'Tabs',
    category: 'content',
    rendererKey: 'tabs_content',
    schemaJson: [
      { key: 'title', label: 'Title', type: 'text' },
      { key: 'items', label: 'Tabs', type: 'list' },
    ],
    defaultPropsJson: {
      title: 'Explore',
      items: [
        { label: 'Overview', body: 'A calm introduction to what this section covers.' },
        { label: 'Details', body: 'Practical notes, timing, and what to expect.' },
        { label: 'FAQ', body: 'Quick answers to the questions we hear most.' },
      ],
    },
    previewJson: { summary: 'Tabbed content panels' },
  },
  {
    key: 'accordion',
    name: 'Accordion',
    category: 'content',
    rendererKey: 'accordion',
    schemaJson: [
      { key: 'eyebrow', label: 'Eyebrow', type: 'text' },
      { key: 'title', label: 'Title', type: 'text' },
      { key: 'items', label: 'Items', type: 'list' },
    ],
    defaultPropsJson: {
      eyebrow: 'Details',
      title: 'Good to know',
      items: [
        { label: 'What’s included', body: 'Accommodation, selected transfers, and planning support.' },
        { label: 'What’s not', body: 'Flights, visas, and personal expenses unless noted.' },
      ],
    },
    previewJson: { summary: 'Generic accordion panels' },
  },
  {
    key: 'timeline',
    name: 'Timeline',
    category: 'content',
    rendererKey: 'timeline',
    schemaJson: [
      { key: 'eyebrow', label: 'Eyebrow', type: 'text' },
      { key: 'title', label: 'Title', type: 'text' },
      { key: 'items', label: 'Steps', type: 'list' },
    ],
    defaultPropsJson: {
      eyebrow: 'Process',
      title: 'How it works',
      items: [
        { title: 'Share your idea', body: 'Dates, budget, and the feeling you want from the trip.' },
        { title: 'We shape options', body: 'A shortlist with clear trade-offs — no fluff.' },
        { title: 'Travel with backup', body: 'We stay reachable while you are away.' },
      ],
    },
    previewJson: { summary: 'Steps / process timeline' },
  },
  {
    key: 'comparison_table',
    name: 'Comparison table',
    category: 'content',
    rendererKey: 'comparison_table',
    schemaJson: [
      { key: 'title', label: 'Title', type: 'text' },
      { key: 'headers', label: 'Column headers (comma-separated)', type: 'text' },
      { key: 'rows', label: 'Rows', type: 'list' },
    ],
    defaultPropsJson: {
      title: 'Compare options',
      headers: 'Feature, Essentials, Signature, Private',
      rows: [
        { cells: 'Trip design, ✓, ✓, ✓' },
        { cells: 'Private guide, —, 1 day, Full' },
        { cells: 'Priority support, —, ✓, ✓' },
      ],
    },
    previewJson: { summary: 'Feature comparison matrix' },
  },
  {
    key: 'image_text_list',
    name: 'Image + text list',
    category: 'content',
    rendererKey: 'image_text_list',
    schemaJson: [
      { key: 'title', label: 'Title', type: 'text' },
      { key: 'items', label: 'Rows', type: 'list' },
    ],
    defaultPropsJson: {
      title: 'Highlights',
      items: [
        {
          image: 'https://images.unsplash.com/photo-1506929562365-f9e4a1d0c5b5?auto=format&fit=crop&w=600&q=80',
          title: 'Coast mornings',
          body: 'Walks before the heat, coffee with a view.',
        },
        {
          image: 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?auto=format&fit=crop&w=600&q=80',
          title: 'Long lunches',
          body: 'Tables that stretch into the afternoon.',
        },
      ],
    },
    previewJson: { summary: 'Repeating image + text rows' },
  },
  {
    key: 'video_feature',
    name: 'Video feature',
    category: 'content',
    rendererKey: 'video_feature',
    schemaJson: [
      { key: 'eyebrow', label: 'Eyebrow', type: 'text' },
      { key: 'title', label: 'Title', type: 'text' },
      { key: 'body', label: 'Body', type: 'textarea' },
      { key: 'videoUrl', label: 'Video embed URL', type: 'url' },
      { key: 'ctaLabel', label: 'CTA label', type: 'text' },
      { key: 'ctaHref', label: 'CTA link', type: 'url' },
    ],
    defaultPropsJson: {
      eyebrow: 'Watch',
      title: 'A glimpse of the place',
      body: 'Sixty seconds that say more than a brochure.',
      videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
      ctaLabel: 'Plan this trip',
      ctaHref: '/contact',
    },
    previewJson: { summary: 'Video + copy feature' },
  },
  {
    key: 'map_block',
    name: 'Map block',
    category: 'content',
    rendererKey: 'map_block',
    schemaJson: [
      { key: 'title', label: 'Title', type: 'text' },
      { key: 'body', label: 'Sidebar text', type: 'textarea' },
      { key: 'mapEmbedUrl', label: 'Map embed URL', type: 'url' },
      { key: 'ctaLabel', label: 'CTA label', type: 'text' },
      { key: 'ctaHref', label: 'CTA link', type: 'url' },
    ],
    defaultPropsJson: {
      title: 'On the map',
      body: 'Central, walkable, and close to the waterfront.',
      mapEmbedUrl: '',
      ctaLabel: 'Get directions',
      ctaHref: '/contact',
    },
    previewJson: { summary: 'Map + sidebar' },
  },
  {
    key: 'footer_columns',
    name: 'Footer columns',
    category: 'layout',
    rendererKey: 'footer_columns',
    schemaJson: [
      { key: 'col1Title', label: 'Column 1 title', type: 'text' },
      { key: 'col1Body', label: 'Column 1 body', type: 'textarea' },
      { key: 'col2Title', label: 'Column 2 title', type: 'text' },
      { key: 'col2Body', label: 'Column 2 body', type: 'textarea' },
      { key: 'col3Title', label: 'Column 3 title', type: 'text' },
      { key: 'col3Body', label: 'Column 3 body', type: 'textarea' },
    ],
    defaultPropsJson: {
      col1Title: 'Explore',
      col1Body: 'Home\nAbout\nContact',
      col2Title: 'Travel',
      col2Body: 'Destinations\nPackages\nJournal',
      col3Title: 'Contact',
      col3Body: 'hello@example.com\n+1 555 0100',
    },
    previewJson: { summary: 'Multi-column footer content' },
  },
  {
    key: 'legal_text',
    name: 'Legal text',
    category: 'content',
    rendererKey: 'legal_text',
    schemaJson: [
      { key: 'title', label: 'Title', type: 'text' },
      { key: 'body', label: 'Body', type: 'textarea', required: true },
      { key: 'updatedAt', label: 'Last updated', type: 'text' },
    ],
    defaultPropsJson: {
      title: 'Privacy policy',
      updatedAt: 'Updated January 2026',
      body: 'We collect only what we need to respond to enquiries and deliver travel services.\n\nWe do not sell personal data. Contact us to request access or deletion.',
    },
    previewJson: { summary: 'Long-form policy / legal body' },
  },
  {
    key: 'cards_carousel',
    name: 'Cards carousel',
    category: 'content',
    rendererKey: 'cards_carousel',
    schemaJson: [
      { key: 'title', label: 'Title', type: 'text' },
      { key: 'items', label: 'Cards', type: 'list' },
    ],
    defaultPropsJson: {
      title: 'Browse',
      items: [
        {
          image: 'https://images.unsplash.com/photo-1506929562365-f9e4a1d0c5b5?auto=format&fit=crop&w=700&q=80',
          title: 'Islands',
          body: 'Slow ferries and clear water.',
          href: '/about',
        },
        {
          image: 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?auto=format&fit=crop&w=700&q=80',
          title: 'Mountains',
          body: 'Cool air and long views.',
          href: '/about',
        },
        {
          image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=700&q=80',
          title: 'Cities',
          body: 'Markets, museums, late dinners.',
          href: '/about',
        },
      ],
    },
    previewJson: { summary: 'Horizontal scroll cards' },
  },
  {
    key: 'banner_slim',
    name: 'Slim banner',
    category: 'conversion',
    rendererKey: 'banner_slim',
    schemaJson: [
      { key: 'text', label: 'Text', type: 'text', required: true },
      { key: 'ctaLabel', label: 'CTA label', type: 'text' },
      { key: 'ctaHref', label: 'CTA link', type: 'url' },
    ],
    defaultPropsJson: {
      text: 'Need a quote this week? We are booking autumn dates now.',
      ctaLabel: 'Request a plan',
      ctaHref: '/contact',
    },
    previewJson: { summary: 'Compact mid-page promo' },
  },
  // ——— Phase 3 ———
  {
    key: 'destination_grid',
    name: 'Destination grid',
    category: 'content',
    rendererKey: 'destination_grid',
    schemaJson: [
      { key: 'eyebrow', label: 'Eyebrow', type: 'text' },
      { key: 'title', label: 'Title', type: 'text' },
      { key: 'items', label: 'Destinations', type: 'list' },
    ],
    defaultPropsJson: {
      eyebrow: 'Go places',
      title: 'Destinations we love',
      items: [
        {
          image: 'https://images.unsplash.com/photo-1506929562365-f9e4a1d0c5b5?auto=format&fit=crop&w=800&q=80',
          name: 'Sri Lanka',
          tagline: 'Tea country to the south coast',
          href: '/about',
        },
        {
          image: 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?auto=format&fit=crop&w=800&q=80',
          name: 'Vietnam',
          tagline: 'Cities, islands, and quiet countryside',
          href: '/about',
        },
      ],
    },
    previewJson: { summary: 'Destination cards' },
  },
  {
    key: 'package_cards',
    name: 'Package cards',
    category: 'conversion',
    rendererKey: 'package_cards',
    schemaJson: [
      { key: 'eyebrow', label: 'Eyebrow', type: 'text' },
      { key: 'title', label: 'Title', type: 'text' },
      { key: 'items', label: 'Packages', type: 'list' },
    ],
    defaultPropsJson: {
      eyebrow: 'Trips',
      title: 'Ready-to-tailor packages',
      items: [
        {
          image: 'https://images.unsplash.com/photo-1506929562365-f9e4a1d0c5b5?auto=format&fit=crop&w=800&q=80',
          name: 'Coastal week',
          price: 'From $1,290',
          nights: '7 nights',
          highlights: 'Beach stay\nOne day tour\nAirport transfers',
          ctaLabel: 'Enquire',
          ctaHref: '/contact',
        },
        {
          image: 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?auto=format&fit=crop&w=800&q=80',
          name: 'Hill escape',
          price: 'From $980',
          nights: '5 nights',
          highlights: 'Tea country lodge\nGuided walks\nTrain journey',
          ctaLabel: 'Enquire',
          ctaHref: '/contact',
        },
      ],
    },
    previewJson: { summary: 'Tour package cards' },
  },
  {
    key: 'itinerary',
    name: 'Itinerary',
    category: 'content',
    rendererKey: 'itinerary',
    schemaJson: [
      { key: 'eyebrow', label: 'Eyebrow', type: 'text' },
      { key: 'title', label: 'Title', type: 'text' },
      { key: 'items', label: 'Days', type: 'list' },
    ],
    defaultPropsJson: {
      eyebrow: 'Sample plan',
      title: 'Day by day',
      items: [
        { day: 'Day 1', title: 'Arrive & settle', body: 'Airport meet, check-in, and a gentle evening walk.' },
        { day: 'Day 2', title: 'Coast road', body: 'Scenic drive with lunch by the water.' },
        { day: 'Day 3', title: 'Free morning', body: 'Optional spa or market — your pace.' },
      ],
    },
    previewJson: { summary: 'Day-by-day itinerary' },
  },
  {
    key: 'hotel_highlight',
    name: 'Hotel highlight',
    category: 'content',
    rendererKey: 'hotel_highlight',
    schemaJson: [
      { key: 'name', label: 'Property name', type: 'text' },
      { key: 'stars', label: 'Stars', type: 'text' },
      { key: 'imageUrl', label: 'Image', type: 'url' },
      { key: 'body', label: 'Description', type: 'textarea' },
      { key: 'amenities', label: 'Amenities (one per line)', type: 'textarea' },
      { key: 'ctaLabel', label: 'CTA label', type: 'text' },
      { key: 'ctaHref', label: 'CTA link', type: 'url' },
    ],
    defaultPropsJson: {
      name: 'Harbour House',
      stars: '4',
      imageUrl: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1200&q=80',
      body: 'A calm boutique stay a short walk from the waterfront.',
      amenities: 'Breakfast\nPool\nWi‑Fi\nAirport transfer available',
      ctaLabel: 'Request this stay',
      ctaHref: '/contact',
    },
    previewJson: { summary: 'Featured hotel / property card' },
  },
  {
    key: 'trip_search_cta',
    name: 'Trip search CTA',
    category: 'conversion',
    rendererKey: 'trip_search_cta',
    schemaJson: [
      { key: 'title', label: 'Title', type: 'text' },
      { key: 'body', label: 'Body', type: 'textarea' },
      { key: 'destinationLabel', label: 'Destination field label', type: 'text' },
      { key: 'datesLabel', label: 'Dates field label', type: 'text' },
      { key: 'ctaLabel', label: 'Button label', type: 'text' },
      { key: 'ctaHref', label: 'Button link', type: 'url' },
    ],
    defaultPropsJson: {
      title: 'Where to next?',
      body: 'Tell us a destination and rough dates — we will take it from there.',
      destinationLabel: 'Destination',
      datesLabel: 'Travel dates',
      ctaLabel: 'Start enquiry',
      ctaHref: '/contact',
    },
    previewJson: { summary: 'Search-style enquiry band' },
  },
  {
    key: 'season_promo',
    name: 'Season promo',
    category: 'conversion',
    rendererKey: 'season_promo',
    schemaJson: [
      { key: 'eyebrow', label: 'Eyebrow', type: 'text' },
      { key: 'title', label: 'Title', type: 'text' },
      { key: 'body', label: 'Body', type: 'textarea' },
      { key: 'imageUrl', label: 'Background image', type: 'url' },
      { key: 'ctaLabel', label: 'CTA label', type: 'text' },
      { key: 'ctaHref', label: 'CTA link', type: 'url' },
    ],
    defaultPropsJson: {
      eyebrow: 'This season',
      title: 'Monsoon rates are live',
      body: 'Lush landscapes, quieter hotels, and softer prices.',
      imageUrl: 'https://images.unsplash.com/photo-1506929562365-f9e4a1d0c5b5?auto=format&fit=crop&w=1400&q=80',
      ctaLabel: 'See offers',
      ctaHref: '/contact',
    },
    previewJson: { summary: 'Seasonal offer banner' },
  },
  {
    key: 'trust_badges',
    name: 'Trust badges',
    category: 'social_proof',
    rendererKey: 'trust_badges',
    schemaJson: [
      { key: 'title', label: 'Title', type: 'text' },
      { key: 'items', label: 'Badges', type: 'list' },
    ],
    defaultPropsJson: {
      title: 'Travel with confidence',
      items: [
        { label: 'Licensed agency', body: 'Fully registered operators' },
        { label: 'Secure payments', body: 'Card & bank transfer' },
        { label: '24/7 line', body: 'On-trip support number' },
      ],
    },
    previewJson: { summary: 'Trust / certification badges' },
  },
  {
    key: 'enquiry_split',
    name: 'Enquiry split',
    category: 'conversion',
    rendererKey: 'enquiry_split',
    schemaJson: [
      { key: 'eyebrow', label: 'Eyebrow', type: 'text' },
      { key: 'title', label: 'Title', type: 'text' },
      { key: 'body', label: 'Selling points', type: 'textarea' },
      { key: 'formKey', label: 'Form key', type: 'select' },
      { key: 'formTitle', label: 'Form title', type: 'text' },
    ],
    defaultPropsJson: {
      eyebrow: 'Enquire',
      title: 'Tell us about your trip',
      body: '• Reply within one business day\n• No obligation quote\n• Tailored to your dates',
      formKey: 'contact',
      formTitle: 'Send a message',
    },
    previewJson: { summary: 'Form + selling points' },
  },
  {
    key: 'gallery_masonry',
    name: 'Gallery masonry',
    category: 'content',
    rendererKey: 'gallery_masonry',
    schemaJson: [
      { key: 'eyebrow', label: 'Eyebrow', type: 'text' },
      { key: 'title', label: 'Title', type: 'text' },
      { key: 'images', label: 'Images', type: 'list' },
    ],
    defaultPropsJson: {
      eyebrow: 'Mood',
      title: 'Places & moments',
      images: [
        {
          url: 'https://images.unsplash.com/photo-1506929562365-f9e4a1d0c5b5?auto=format&fit=crop&w=900&q=80',
          alt: 'Coast',
        },
        {
          url: 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?auto=format&fit=crop&w=900&q=80',
          alt: 'Pool',
        },
        {
          url: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=900&q=80',
          alt: 'Lobby',
        },
        {
          url: 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?auto=format&fit=crop&w=900&q=80',
          alt: 'Room',
        },
      ],
    },
    previewJson: { summary: 'Masonry travel photo mosaic' },
  },
  {
    key: 'route_map',
    name: 'Route map',
    category: 'content',
    rendererKey: 'route_map',
    schemaJson: [
      { key: 'eyebrow', label: 'Eyebrow', type: 'text' },
      { key: 'title', label: 'Title', type: 'text' },
      { key: 'items', label: 'Stops', type: 'list' },
      { key: 'mapEmbedUrl', label: 'Map embed URL', type: 'url' },
    ],
    defaultPropsJson: {
      eyebrow: 'Route',
      title: 'Where you will go',
      items: [
        { title: 'Arrive — Capital', body: 'Night 1–2' },
        { title: 'Hill country', body: 'Night 3–5' },
        { title: 'South coast', body: 'Night 6–8' },
      ],
      mapEmbedUrl: '',
    },
    previewJson: { summary: 'Stops list + optional map' },
  },
] as const;
