import { TRAVEL_REQUEST_PERMISSIONS } from '../capabilities';
import { AGENCY_ROUTES } from '../agencyRoutes';
import type { AgencyWorkspace, UiCapability } from './types';
import { NEW_TRAVEL_REQUEST_ROUTE } from './types';

/**
 * Agency OS UI capability registry — Progressive Complexity 1.0 foundation.
 *
 * Extend this table instead of scattering role conditionals across components.
 * Action capabilities reference `CAP` permission keys via inline permission arrays.
 */
export const AGENCY_UI_CAPABILITIES: readonly UiCapability[] = [
  // --- Create / home ---
  {
    key: 'agency.travel_request.create',
    label: 'New customer call',
    route: NEW_TRAVEL_REQUEST_ROUTE,
    icon: 'Plus',
    allowedOrgKinds: ['travel_agency', 'dmc'],
    allowedWorkspaces: ['owner', 'sales_manager', 'sales_executive', 'travel_consultant'],
    requiredAllPermissions: TRAVEL_REQUEST_PERMISSIONS,
    disclosureLevel: 'primary',
    navigationGroup: 'Home',
    isCreateAction: true,
    /** Global header hosts the create CTA — do not duplicate in sidebar. */
    showInNavigation: false,
    priority: 1,
  },
  {
    key: 'agency.home',
    label: 'Home',
    route: '/',
    icon: 'LayoutDashboard',
    allowedOrgKinds: ['travel_agency', 'dmc'],
    disclosureLevel: 'primary',
    navigationGroup: 'Home',
    priority: 0,
    workspaceLabels: {
      owner: 'Dashboard',
      sales_manager: 'Sales overview',
      sales_executive: 'Home',
      travel_consultant: 'Planning home',
      operations: 'Operations home',
      finance: 'Finance home',
      auditor: 'Audit overview',
    },
  },

  // --- Sales executive / manager ---
  {
    key: 'agency.requests.mine',
    label: 'Travel requests',
    route: AGENCY_ROUTES.workRequests,
    icon: 'Contact',
    allowedOrgKinds: ['travel_agency', 'dmc'],
    allowedWorkspaces: ['sales_executive'],
    requiredAnyPermissions: ['inquiry.read'],
    disclosureLevel: 'primary',
    navigationGroup: 'Sales',
    priority: 10,
  },
  {
    key: 'agency.requests.team',
    label: 'Travel requests',
    route: AGENCY_ROUTES.workRequests,
    icon: 'Contact',
    allowedOrgKinds: ['travel_agency', 'dmc'],
    allowedWorkspaces: ['sales_manager', 'owner'],
    requiredAnyPermissions: ['inquiry.read'],
    disclosureLevel: 'primary',
    navigationGroup: 'Sales',
    priority: 10,
  },
  {
    key: 'agency.inbox',
    label: 'Inbox',
    route: AGENCY_ROUTES.inbox,
    icon: 'Inbox',
    allowedOrgKinds: ['travel_agency', 'dmc'],
    allowedWorkspaces: ['sales_executive', 'sales_manager', 'owner', 'auditor'],
    requiredAnyPermissions: ['lead.read', 'lead.read.own', 'inquiry.read'],
    disclosureLevel: 'primary',
    // Work (not a separate section) so Inbox stays near the top of the daily spine.
    navigationGroup: 'Sales',
    priority: 5,
    workspaceLabels: {
      sales_executive: 'Inbox',
      sales_manager: 'Team inbox',
      owner: 'Inbox',
    },
  },
  {
    key: 'agency.leads',
    label: 'Leads',
    route: AGENCY_ROUTES.leads,
    icon: 'Users',
    allowedOrgKinds: ['travel_agency', 'dmc'],
    allowedWorkspaces: ['sales_executive', 'sales_manager', 'owner', 'auditor'],
    requiredAnyPermissions: ['lead.read', 'lead.read.own'],
    disclosureLevel: 'primary',
    navigationGroup: 'Sales',
    priority: 20,
  },
  {
    key: 'agency.followups',
    label: 'Follow-ups',
    route: AGENCY_ROUTES.workFollowUps,
    icon: 'CheckSquare',
    allowedOrgKinds: ['travel_agency', 'dmc'],
    allowedWorkspaces: ['sales_executive', 'sales_manager'],
    requiredAnyPermissions: ['task.read'],
    disclosureLevel: 'primary',
    navigationGroup: 'Sales',
    priority: 30,
  },
  {
    key: 'agency.team_followups',
    label: 'Team follow-ups',
    route: AGENCY_ROUTES.workFollowUps,
    icon: 'CheckSquare',
    allowedOrgKinds: ['travel_agency', 'dmc'],
    allowedWorkspaces: ['sales_manager', 'owner'],
    requiredAnyPermissions: ['task.read'],
    disclosureLevel: 'primary',
    navigationGroup: 'Sales',
    priority: 35,
  },
  {
    key: 'agency.planning',
    label: 'Planning',
    route: AGENCY_ROUTES.workPlanning,
    icon: 'ClipboardList',
    allowedOrgKinds: ['travel_agency', 'dmc'],
    allowedWorkspaces: ['sales_executive', 'sales_manager', 'owner'],
    requiredAnyPermissions: ['inquiry.read'],
    disclosureLevel: 'primary',
    navigationGroup: 'Sales',
    priority: 40,
  },
  {
    key: 'agency.quotations',
    label: 'Quotes',
    route: AGENCY_ROUTES.workQuotations,
    icon: 'FileText',
    allowedOrgKinds: ['travel_agency', 'dmc'],
    allowedWorkspaces: ['sales_executive', 'sales_manager', 'owner'],
    requiredAnyPermissions: ['trip.read', 'quote.read'],
    disclosureLevel: 'primary',
    navigationGroup: 'Sales',
    priority: 50,
  },
  {
    key: 'agency.customers',
    label: 'Customers',
    route: AGENCY_ROUTES.businessCustomers,
    icon: 'Building2',
    allowedOrgKinds: ['travel_agency', 'dmc'],
    allowedWorkspaces: ['sales_manager', 'owner', 'sales_executive', 'finance'],
    requiredAnyPermissions: ['party.read'],
    disclosureLevel: 'primary',
    navigationGroup: 'Sales',
    priority: 60,
    workspaceLabels: {
      sales_executive: 'My customers',
      owner: 'Customers',
    },
  },
  {
    key: 'agency.sales_reports',
    label: 'Sales reports',
    route: '/',
    icon: 'BarChart3',
    allowedOrgKinds: ['travel_agency', 'dmc'],
    allowedWorkspaces: ['sales_manager'],
    requiredAnyPermissions: ['report.sales.read'],
    disclosureLevel: 'primary',
    navigationGroup: 'Sales',
    priority: 70,
    showInNavigation: false,
  },

  // --- Travel consultant ---
  {
    key: 'agency.assigned_requests',
    label: 'Travel requests',
    route: AGENCY_ROUTES.workRequests,
    icon: 'Contact',
    allowedOrgKinds: ['travel_agency', 'dmc'],
    allowedWorkspaces: ['travel_consultant'],
    requiredAnyPermissions: ['inquiry.read'],
    disclosureLevel: 'primary',
    navigationGroup: 'Sales',
    priority: 10,
  },
  {
    key: 'agency.requirements',
    label: 'Planning',
    route: AGENCY_ROUTES.workPlanning,
    icon: 'ClipboardList',
    allowedOrgKinds: ['travel_agency', 'dmc'],
    allowedWorkspaces: ['travel_consultant'],
    requiredAnyPermissions: ['inquiry.read'],
    disclosureLevel: 'primary',
    navigationGroup: 'Sales',
    priority: 20,
  },
  {
    key: 'agency.itineraries',
    label: 'Itineraries',
    route: AGENCY_ROUTES.trips,
    icon: 'Map',
    allowedOrgKinds: ['travel_agency', 'dmc'],
    allowedWorkspaces: ['travel_consultant'],
    requiredAnyPermissions: ['trip.read'],
    disclosureLevel: 'primary',
    navigationGroup: 'Trips & operations',
    priority: 30,
  },
  {
    key: 'agency.quotation_drafts',
    label: 'Quote drafts',
    route: AGENCY_ROUTES.workQuotationDrafts,
    icon: 'FileText',
    allowedOrgKinds: ['travel_agency', 'dmc'],
    allowedWorkspaces: ['travel_consultant'],
    requiredAnyPermissions: ['quote.read', 'trip.read'],
    disclosureLevel: 'primary',
    navigationGroup: 'Sales',
    priority: 40,
  },
  {
    key: 'agency.templates',
    label: 'Templates',
    route: '/rates',
    icon: 'BookOpen',
    allowedOrgKinds: ['travel_agency', 'dmc'],
    allowedWorkspaces: ['travel_consultant'],
    requiredAnyPermissions: ['quote.read'],
    disclosureLevel: 'primary',
    navigationGroup: 'Products & suppliers',
    priority: 50,
  },

  // --- Operations ---
  {
    key: 'agency.upcoming_trips',
    label: 'Upcoming trips',
    route: AGENCY_ROUTES.trips,
    icon: 'Plane',
    allowedOrgKinds: ['travel_agency', 'dmc'],
    allowedWorkspaces: ['operations', 'owner'],
    requiredAnyPermissions: ['trip.read'],
    disclosureLevel: 'primary',
    navigationGroup: 'Trips & operations',
    priority: 10,
    workspaceLabels: { owner: 'Trips' },
  },
  {
    key: 'agency.operations_centre',
    label: 'Operations',
    route: AGENCY_ROUTES.operations,
    icon: 'ClipboardList',
    allowedOrgKinds: ['travel_agency', 'dmc'],
    allowedWorkspaces: ['operations', 'owner'],
    requiredAnyPermissions: ['ops.read'],
    disclosureLevel: 'primary',
    navigationGroup: 'Trips & operations',
    priority: 20,
    workspaceLabels: { owner: 'Operations' },
  },
  {
    key: 'agency.bookings',
    label: 'Bookings',
    route: AGENCY_ROUTES.operationsBookings,
    icon: 'CalendarCheck',
    allowedOrgKinds: ['travel_agency', 'dmc'],
    allowedWorkspaces: ['operations', 'owner'],
    requiredAnyPermissions: ['trip.read', 'ops.read'],
    disclosureLevel: 'primary',
    navigationGroup: 'Trips & operations',
    priority: 30,
    /** Filtered Operations view — deep-linked from dashboard, not a sidebar twin. */
    showInNavigation: false,
  },
  {
    key: 'agency.movement_board',
    label: 'Movement board',
    route: AGENCY_ROUTES.operationsMovement,
    icon: 'Map',
    allowedOrgKinds: ['travel_agency', 'dmc'],
    allowedWorkspaces: ['operations', 'owner'],
    requiredAnyPermissions: ['ops.read', 'trip.read'],
    disclosureLevel: 'primary',
    navigationGroup: 'Trips & operations',
    priority: 35,
    workspaceLabels: { owner: 'Movement board' },
  },
  {
    key: 'agency.supplier_requests',
    label: 'Supplier requests',
    route: AGENCY_ROUTES.operationsSuppliers,
    icon: 'Truck',
    allowedOrgKinds: ['travel_agency', 'dmc'],
    allowedWorkspaces: ['operations'],
    requiredAnyPermissions: ['ops.read'],
    disclosureLevel: 'primary',
    navigationGroup: 'Trips & operations',
    priority: 40,
  },
  {
    key: 'agency.travellers',
    label: 'Clients',
    route: '/parties',
    icon: 'Users',
    allowedOrgKinds: ['travel_agency', 'dmc'],
    allowedWorkspaces: ['operations'],
    requiredAnyPermissions: ['party.read'],
    disclosureLevel: 'primary',
    navigationGroup: 'Trips & operations',
    priority: 50,
  },
  {
    key: 'agency.incidents',
    label: 'Alerts & risks',
    route: AGENCY_ROUTES.operationsIncidents,
    icon: 'AlertTriangle',
    allowedOrgKinds: ['travel_agency', 'dmc'],
    allowedWorkspaces: ['operations', 'owner'],
    requiredAnyPermissions: ['incident.manage', 'ops.read'],
    disclosureLevel: 'primary',
    navigationGroup: 'Trips & operations',
    priority: 60,
    workspaceLabels: { owner: 'Alerts & risks' },
  },
  {
    key: 'agency.tasks_ops',
    label: 'Tasks',
    route: AGENCY_ROUTES.tasks,
    icon: 'CheckSquare',
    allowedOrgKinds: ['travel_agency', 'dmc'],
    allowedWorkspaces: ['operations'],
    requiredAnyPermissions: ['task.read'],
    disclosureLevel: 'secondary',
    navigationGroup: 'Trips & operations',
    priority: 70,
  },

  // --- Finance ---
  {
    key: 'agency.receivables',
    label: 'Invoices & payments',
    route: AGENCY_ROUTES.finance,
    icon: 'Wallet',
    allowedOrgKinds: ['travel_agency', 'dmc'],
    allowedWorkspaces: ['finance', 'owner'],
    requiredAnyPermissions: ['finance.cost.read'],
    disclosureLevel: 'primary',
    navigationGroup: 'Finance',
    priority: 10,
    workspaceLabels: { owner: 'Invoices & payments' },
  },
  {
    key: 'agency.overdue',
    label: 'Overdue',
    route: AGENCY_ROUTES.financeOverdue,
    icon: 'AlertCircle',
    allowedOrgKinds: ['travel_agency', 'dmc'],
    allowedWorkspaces: ['finance'],
    requiredAnyPermissions: ['finance.cost.read'],
    disclosureLevel: 'primary',
    navigationGroup: 'Finance',
    priority: 20,
  },
  {
    key: 'agency.supplier_payables',
    label: 'Supplier payables',
    route: AGENCY_ROUTES.financePayables,
    icon: 'IndianRupee',
    allowedOrgKinds: ['travel_agency', 'dmc'],
    allowedWorkspaces: ['finance'],
    requiredAnyPermissions: ['finance.settlement.read', 'finance.cost.read'],
    disclosureLevel: 'primary',
    navigationGroup: 'Finance',
    priority: 30,
  },
  {
    key: 'agency.portfolio_profitability',
    label: 'Profitability',
    route: AGENCY_ROUTES.financeProfitability,
    icon: 'BarChart3',
    allowedOrgKinds: ['travel_agency', 'dmc'],
    allowedWorkspaces: ['finance', 'owner'],
    requiredAnyPermissions: ['finance.margin.read', 'finance.cost.read'],
    disclosureLevel: 'primary',
    navigationGroup: 'Finance',
    priority: 35,
    workspaceLabels: { owner: 'Profitability' },
  },
  {
    key: 'agency.reconciliation',
    label: 'Reconciliation',
    route: AGENCY_ROUTES.financeReconciliation,
    icon: 'Scale',
    allowedOrgKinds: ['travel_agency', 'dmc'],
    allowedWorkspaces: ['finance'],
    requiredAnyPermissions: ['finance.payment.manage', 'finance.cost.read'],
    disclosureLevel: 'secondary',
    navigationGroup: 'Finance',
    priority: 40,
  },

  // --- Auditor ---
  {
    key: 'agency.audit_trips',
    label: 'Trips',
    route: AGENCY_ROUTES.trips,
    icon: 'Plane',
    allowedOrgKinds: ['travel_agency', 'dmc'],
    allowedWorkspaces: ['auditor'],
    requiredAnyPermissions: ['trip.read'],
    disclosureLevel: 'primary',
    navigationGroup: 'Audit',
    priority: 10,
  },
  {
    key: 'agency.audit_quotations',
    label: 'Quotes',
    route: AGENCY_ROUTES.workQuotations,
    icon: 'FileText',
    allowedOrgKinds: ['travel_agency', 'dmc'],
    allowedWorkspaces: ['auditor'],
    requiredAnyPermissions: ['quote.read'],
    disclosureLevel: 'primary',
    navigationGroup: 'Audit',
    priority: 20,
  },
  {
    key: 'agency.audit_documents',
    label: 'Commercial documents',
    route: AGENCY_ROUTES.financeDocuments,
    icon: 'FileText',
    allowedOrgKinds: ['travel_agency', 'dmc'],
    allowedWorkspaces: ['auditor'],
    requiredAnyPermissions: ['finance.cost.read'],
    disclosureLevel: 'primary',
    navigationGroup: 'Audit',
    priority: 30,
  },
  {
    key: 'agency.audit_payments',
    label: 'Payments',
    route: AGENCY_ROUTES.financePayments,
    icon: 'Wallet',
    allowedOrgKinds: ['travel_agency', 'dmc'],
    allowedWorkspaces: ['auditor'],
    requiredAnyPermissions: ['finance.cost.read'],
    disclosureLevel: 'primary',
    navigationGroup: 'Audit',
    priority: 40,
  },
  {
    key: 'agency.audit_log',
    label: 'Audit log',
    route: AGENCY_ROUTES.settingsAudit,
    icon: 'ScrollText',
    allowedOrgKinds: ['travel_agency', 'dmc'],
    allowedWorkspaces: ['auditor', 'owner'],
    requiredAnyPermissions: ['audit.read'],
    disclosureLevel: 'primary',
    navigationGroup: 'Administration',
    priority: 50,
  },

  // --- Owner cross-cutting ---
  {
    key: 'agency.sales',
    label: 'Sales dashboard',
    route: AGENCY_ROUTES.businessSales,
    icon: 'Contact',
    allowedOrgKinds: ['travel_agency', 'dmc'],
    allowedWorkspaces: ['owner'],
    requiredAnyPermissions: ['inquiry.read'],
    disclosureLevel: 'secondary',
    navigationGroup: 'Sales',
    priority: 15,
  },
  {
    key: 'agency.team_members',
    label: 'Team',
    route: AGENCY_ROUTES.teamMembers,
    icon: 'Users',
    allowedOrgKinds: ['travel_agency', 'dmc'],
    allowedWorkspaces: ['owner', 'sales_manager'],
    requiredAnyPermissions: ['user.manage'],
    disclosureLevel: 'primary',
    navigationGroup: 'Administration',
    priority: 81,
  },
  {
    key: 'agency.team_roles',
    label: 'Roles',
    route: AGENCY_ROUTES.teamRoles,
    icon: 'Shield',
    allowedOrgKinds: ['travel_agency', 'dmc'],
    allowedWorkspaces: ['owner', 'sales_manager'],
    requiredAnyPermissions: ['user.manage'],
    disclosureLevel: 'primary',
    navigationGroup: 'Administration',
    priority: 82,
  },
  {
    key: 'agency.team_permissions',
    label: 'Permissions',
    route: AGENCY_ROUTES.teamPermissions,
    icon: 'ShieldCheck',
    allowedOrgKinds: ['travel_agency', 'dmc'],
    allowedWorkspaces: ['owner', 'sales_manager'],
    requiredAnyPermissions: ['user.manage'],
    disclosureLevel: 'primary',
    navigationGroup: 'Administration',
    priority: 83,
  },
  {
    key: 'agency.integrations',
    label: 'Integrations',
    route: AGENCY_ROUTES.settingsIntegrations,
    icon: 'Plug',
    allowedOrgKinds: ['travel_agency', 'dmc'],
    allowedWorkspaces: ['owner'],
    requiredAnyPermissions: ['org.settings.read'],
    disclosureLevel: 'primary',
    navigationGroup: 'Growth',
    priority: 10,
  },
  {
    key: 'agency.presence',
    label: 'Website',
    route: AGENCY_ROUTES.settingsPresence,
    icon: 'Globe',
    allowedOrgKinds: ['travel_agency', 'dmc'],
    allowedWorkspaces: ['owner'],
    requiredAnyPermissions: ['org.settings.read'],
    disclosureLevel: 'primary',
    navigationGroup: 'Growth',
    priority: 9,
  },
  {
    key: 'agency.lead-sources',
    label: 'Lead sources',
    route: AGENCY_ROUTES.settingsLeadSources,
    icon: 'Tags',
    allowedOrgKinds: ['travel_agency', 'dmc'],
    allowedWorkspaces: ['owner', 'sales_manager'],
    requiredAnyPermissions: ['org.settings.read', 'lead.read'],
    disclosureLevel: 'secondary',
    navigationGroup: 'Growth',
    priority: 11,
  },

  // --- Secondary / canonical modules ---
  {
    key: 'agency.inquiries',
    label: 'Inquiries',
    route: AGENCY_ROUTES.inquiries,
    icon: 'Contact',
    allowedOrgKinds: ['travel_agency', 'dmc'],
    allowedWorkspaces: ['sales_executive', 'sales_manager', 'owner', 'travel_consultant'],
    requiredAnyPermissions: ['inquiry.read'],
    disclosureLevel: 'secondary',
    navigationGroup: 'Sales',
    priority: 20,
  },
  {
    key: 'agency.trips',
    label: 'Trips',
    route: AGENCY_ROUTES.trips,
    icon: 'Plane',
    allowedOrgKinds: ['travel_agency', 'dmc'],
    allowedWorkspaces: ['sales_executive', 'sales_manager', 'owner'],
    requiredAnyPermissions: ['trip.read'],
    disclosureLevel: 'secondary',
    navigationGroup: 'Trips & operations',
    priority: 30,
  },
  {
    key: 'agency.parties',
    label: 'Clients',
    route: AGENCY_ROUTES.parties,
    icon: 'Building2',
    allowedOrgKinds: ['travel_agency', 'dmc'],
    allowedWorkspaces: ['owner', 'finance', 'sales_manager'],
    requiredAnyPermissions: ['party.read'],
    disclosureLevel: 'secondary',
    navigationGroup: 'Sales',
    priority: 25,
  },
  {
    key: 'agency.tasks',
    label: 'Tasks',
    route: AGENCY_ROUTES.tasks,
    icon: 'CheckSquare',
    allowedOrgKinds: ['travel_agency', 'dmc'],
    requiredAnyPermissions: ['task.read'],
    disclosureLevel: 'secondary',
    navigationGroup: 'Sales',
    priority: 40,
  },
  {
    key: 'agency.places',
    label: 'Destinations',
    route: '/places',
    icon: 'MapPin',
    allowedOrgKinds: ['travel_agency', 'dmc'],
    requiredAnyPermissions: ['trip.read'],
    disclosureLevel: 'secondary',
    navigationGroup: 'Products & suppliers',
    priority: 50,
  },

  // --- Advanced / manage ---
  {
    key: 'agency.network',
    label: 'Partner network',
    route: '/network',
    icon: 'Network',
    allowedOrgKinds: ['travel_agency', 'dmc'],
    allowedWorkspaces: ['owner', 'sales_manager'],
    requiredAnyPermissions: ['network.read'],
    disclosureLevel: 'advanced',
    navigationGroup: 'Products & suppliers',
    priority: 10,
  },
  {
    key: 'agency.suppliers',
    label: 'Suppliers',
    route: '/suppliers',
    icon: 'Truck',
    allowedOrgKinds: ['travel_agency', 'dmc'],
    allowedWorkspaces: ['owner', 'operations', 'sales_manager'],
    requiredAnyPermissions: ['network.read'],
    disclosureLevel: 'advanced',
    navigationGroup: 'Products & suppliers',
    priority: 20,
    workspaceLabels: { operations: 'Suppliers' },
  },
  {
    key: 'agency.rates',
    label: 'Products & rates',
    route: '/rates',
    icon: 'IndianRupee',
    allowedOrgKinds: ['travel_agency', 'dmc'],
    allowedWorkspaces: ['owner', 'travel_consultant', 'sales_manager'],
    requiredAnyPermissions: ['quote.read'],
    disclosureLevel: 'advanced',
    navigationGroup: 'Products & suppliers',
    priority: 30,
  },
  {
    key: 'agency.settings',
    label: 'Settings',
    route: '/settings',
    icon: 'Settings',
    allowedOrgKinds: ['travel_agency', 'dmc'],
    requiredAnyPermissions: ['org.settings.read'],
    disclosureLevel: 'advanced',
    navigationGroup: 'Administration',
    priority: 90,
  },
] as const;

const capabilityByKey = new Map(AGENCY_UI_CAPABILITIES.map((c) => [c.key, c]));

export function getUiCapability(key: string): UiCapability | undefined {
  return capabilityByKey.get(key);
}

/**
 * Ordered capability keys per workspace and disclosure band.
 * The composer resolves permissions and de-duplicates routes.
 */
export const WORKSPACE_NAV_PROFILES: Record<
  AgencyWorkspace,
  { primary: readonly string[]; secondary?: readonly string[]; advanced?: readonly string[] }
> = {
  sales_executive: {
    // Sell spine: home → inbox → follow-ups → leads → customers → quotes → trips
    primary: [
      'agency.home',
      'agency.inbox',
      'agency.followups',
      'agency.leads',
      'agency.customers',
      'agency.quotations',
      'agency.trips',
    ],
    secondary: [
      'agency.requests.mine',
      'agency.planning',
      'agency.tasks',
    ],
    advanced: ['agency.rates', 'agency.network', 'agency.settings'],
  },
  sales_manager: {
    primary: [
      'agency.home',
      'agency.inbox',
      'agency.team_followups',
      'agency.leads',
      'agency.customers',
      'agency.quotations',
      'agency.trips',
    ],
    secondary: [
      'agency.requests.team',
      'agency.planning',
      'agency.team_members',
      'agency.team_roles',
    ],
    advanced: [
      'agency.suppliers',
      'agency.rates',
      'agency.network',
      'agency.settings',
    ],
  },
  travel_consultant: {
    primary: [
      'agency.home',
      'agency.assigned_requests',
      'agency.requirements',
      'agency.itineraries',
      'agency.quotation_drafts',
    ],
    secondary: ['agency.tasks', 'agency.places'],
    advanced: ['agency.rates', 'agency.suppliers', 'agency.settings'],
  },
  operations: {
    primary: [
      'agency.home',
      'agency.upcoming_trips',
      'agency.operations_centre',
      'agency.movement_board',
      'agency.incidents',
      'agency.suppliers',
    ],
    secondary: [
      'agency.supplier_requests',
      'agency.travellers',
      'agency.tasks_ops',
    ],
    advanced: ['agency.places', 'agency.settings'],
  },
  finance: {
    primary: [
      'agency.home',
      'agency.receivables',
      'agency.overdue',
      'agency.supplier_payables',
      'agency.portfolio_profitability',
    ],
    secondary: ['agency.reconciliation', 'agency.trips', 'agency.customers'],
    advanced: ['agency.settings'],
  },
  auditor: {
    primary: [
      'agency.home',
      'agency.audit_trips',
      'agency.audit_quotations',
      'agency.audit_documents',
      'agency.audit_payments',
      'agency.audit_log',
    ],
    secondary: ['agency.inquiries', 'agency.leads'],
  },
  owner: {
    // Sell → operate → settle → supply; admin/growth below the fold
    primary: [
      'agency.home',
      'agency.inbox',
      'agency.leads',
      'agency.customers',
      'agency.quotations',
      'agency.upcoming_trips',
      'agency.operations_centre',
      'agency.movement_board',
      'agency.incidents',
      'agency.receivables',
      'agency.portfolio_profitability',
      'agency.suppliers',
      'agency.rates',
    ],
    secondary: [
      'agency.tasks',
      'agency.places',
      'agency.network',
      'agency.team_members',
      'agency.team_roles',
      'agency.team_permissions',
    ],
    advanced: [
      'agency.presence',
      'agency.integrations',
      'agency.audit_log',
      'agency.settings',
    ],
  },
};
