import type { SystemPlaceNode } from './system-places';

/**
 * North East + West Bengal / Sikkim hierarchy places.
 * Merged into SYSTEM_PLACES (order: parents before children via seed passes).
 */
export const SYSTEM_PLACES_NORTHEAST: SystemPlaceNode[] = [
  // ── States / regions ───────────────────────────────────────────────
  {
    name: 'West Bengal',
    key: 'west-bengal',
    kind: 'state',
    parentKey: 'india',
    country: 'India',
    region: 'East',
    domesticOrIntl: 'domestic',
    subcategoryKeys: ['hill-circuit', 'heritage-circuit'],
  },
  {
    name: 'Sikkim',
    key: 'sikkim',
    kind: 'state',
    parentKey: 'india',
    country: 'India',
    region: 'East',
    domesticOrIntl: 'domestic',
    subcategoryKeys: ['hill-circuit', 'himalayan'],
  },
  {
    name: 'Assam',
    key: 'assam',
    kind: 'state',
    parentKey: 'india',
    country: 'India',
    region: 'Northeast',
    domesticOrIntl: 'domestic',
    subcategoryKeys: ['wildlife-circuit', 'hill-circuit'],
  },
  {
    name: 'Meghalaya',
    key: 'meghalaya',
    kind: 'state',
    parentKey: 'india',
    country: 'India',
    region: 'Northeast',
    domesticOrIntl: 'domestic',
    subcategoryKeys: ['hill-circuit', 'wildlife-circuit'],
  },
  {
    name: 'Arunachal Pradesh',
    key: 'arunachal-pradesh',
    kind: 'state',
    parentKey: 'india',
    country: 'India',
    region: 'Northeast',
    domesticOrIntl: 'domestic',
    subcategoryKeys: ['himalayan', 'hill-circuit'],
  },
  {
    name: 'Nagaland',
    key: 'nagaland',
    kind: 'state',
    parentKey: 'india',
    country: 'India',
    region: 'Northeast',
    domesticOrIntl: 'domestic',
    subcategoryKeys: ['heritage-circuit'],
  },
  {
    name: 'Manipur',
    key: 'manipur',
    kind: 'state',
    parentKey: 'india',
    country: 'India',
    region: 'Northeast',
    domesticOrIntl: 'domestic',
    subcategoryKeys: ['heritage-circuit'],
  },
  {
    name: 'Mizoram',
    key: 'mizoram',
    kind: 'state',
    parentKey: 'india',
    country: 'India',
    region: 'Northeast',
    domesticOrIntl: 'domestic',
    subcategoryKeys: ['hill-circuit'],
  },
  {
    name: 'Tripura',
    key: 'tripura',
    kind: 'state',
    parentKey: 'india',
    country: 'India',
    region: 'Northeast',
    domesticOrIntl: 'domestic',
    subcategoryKeys: ['heritage-circuit'],
  },
  {
    name: 'Kolkata',
    key: 'kolkata',
    kind: 'city',
    parentKey: 'west-bengal',
    country: 'India',
    region: 'East',
    domesticOrIntl: 'domestic',
    subcategoryKeys: ['heritage-circuit'],
    profile: {
      description:
        'Cultural capital of East India — gateway flights to the North East and North Bengal hills.',
      latitude: 22.5726,
      longitude: 88.3639,
      suitabilityTags: ['city', 'gateway', 'culture'],
      googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Kolkata',
    },
  },

  // ── Sikkim cities ──────────────────────────────────────────────────
  {
    name: 'Pelling',
    key: 'pelling',
    kind: 'city',
    parentKey: 'sikkim',
    country: 'India',
    region: 'East',
    domesticOrIntl: 'domestic',
    subcategoryKeys: ['himalayan', 'hill-circuit'],
    profile: {
      description:
        'West Sikkim base for Kanchenjunga views, Pemayangtse, and skywalk — often paired with Gangtok.',
      latitude: 27.3191,
      longitude: 88.2403,
      bestTime: 'March–June and October–December',
      suitabilityTags: ['honeymoon', 'viewpoint', 'sikkim'],
      googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Pelling+Sikkim',
    },
  },
  {
    name: 'Namchi',
    key: 'namchi',
    kind: 'city',
    parentKey: 'sikkim',
    country: 'India',
    region: 'East',
    domesticOrIntl: 'domestic',
    subcategoryKeys: ['himalayan', 'hill-circuit'],
    profile: {
      description: 'South Sikkim town known for Char Dham complex and hillside vistas.',
      latitude: 27.1645,
      longitude: 88.3639,
      suitabilityTags: ['family', 'pilgrimage', 'sikkim'],
      googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Namchi+Sikkim',
    },
  },
  {
    name: 'Ravangla',
    key: 'ravangla',
    kind: 'city',
    parentKey: 'sikkim',
    country: 'India',
    region: 'East',
    domesticOrIntl: 'domestic',
    subcategoryKeys: ['himalayan'],
    profile: {
      description: 'Buddha Park (Tathagata Tsal) and misty South Sikkim ridge town.',
      latitude: 27.308,
      longitude: 88.363,
      suitabilityTags: ['family', 'monastery', 'sikkim'],
      googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Ravangla+Sikkim',
    },
  },
  {
    name: 'Lachung',
    key: 'lachung',
    kind: 'city',
    parentKey: 'sikkim',
    country: 'India',
    region: 'East',
    domesticOrIntl: 'domestic',
    subcategoryKeys: ['himalayan'],
    profile: {
      description: 'North Sikkim valley gateway toward Yumthang — permits required.',
      latitude: 27.689,
      longitude: 88.743,
      suitabilityTags: ['adventure', 'sikkim', 'permits'],
      googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Lachung+Sikkim',
    },
  },
  {
    name: 'Lachen',
    key: 'lachen',
    kind: 'city',
    parentKey: 'sikkim',
    country: 'India',
    region: 'East',
    domesticOrIntl: 'domestic',
    subcategoryKeys: ['himalayan'],
    profile: {
      description: 'North Sikkim base for Gurudongmar excursions — cold and permit-gated.',
      latitude: 27.7167,
      longitude: 88.55,
      suitabilityTags: ['adventure', 'sikkim', 'permits'],
      googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Lachen+Sikkim',
    },
  },

  // ── Sikkim landmarks ───────────────────────────────────────────────
  {
    name: 'MG Marg',
    key: 'mg-marg-gangtok',
    kind: 'landmark',
    parentKey: 'gangtok',
    country: 'India',
    region: 'East',
    domesticOrIntl: 'domestic',
    subcategoryKeys: ['himalayan'],
    profile: {
      description: 'Gangtok’s vehicle-free promenade — cafés, shops, and evening strolls.',
      latitude: 27.3314,
      longitude: 88.6138,
      durationMin: 90,
      suitabilityTags: ['evening', 'shopping', 'family'],
      googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=MG+Marg+Gangtok',
    },
  },
  {
    name: 'Tsomgo Lake',
    key: 'tsomgo-lake',
    kind: 'landmark',
    parentKey: 'gangtok',
    country: 'India',
    region: 'East',
    domesticOrIntl: 'domestic',
    subcategoryKeys: ['himalayan'],
    profile: {
      description: 'High-altitude glacial lake on the Nathula axis — classic Gangtok day trip.',
      latitude: 27.375,
      longitude: 88.764,
      durationMin: 240,
      bestTime: 'Clear mornings; snow possible in winter',
      suitabilityTags: ['day-trip', 'lake', 'permits'],
      googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Tsomgo+Lake',
    },
  },
  {
    name: 'Baba Mandir',
    key: 'baba-mandir',
    kind: 'landmark',
    parentKey: 'gangtok',
    country: 'India',
    region: 'East',
    domesticOrIntl: 'domestic',
    subcategoryKeys: ['himalayan'],
    profile: {
      description: 'Memorial shrine beyond Tsomgo — often combined on East Sikkim day tours.',
      latitude: 27.368,
      longitude: 88.845,
      durationMin: 60,
      suitabilityTags: ['day-trip', 'pilgrimage'],
      googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Baba+Mandir+Sikkim',
    },
  },
  {
    name: 'Rumtek Monastery',
    key: 'rumtek-monastery',
    kind: 'landmark',
    parentKey: 'gangtok',
    country: 'India',
    region: 'East',
    domesticOrIntl: 'domestic',
    subcategoryKeys: ['himalayan'],
    profile: {
      description: 'Seat of the Karmapa lineage — prayer halls and valley views near Gangtok.',
      latitude: 27.2896,
      longitude: 88.5615,
      durationMin: 120,
      suitabilityTags: ['monastery', 'culture', 'family'],
      googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Rumtek+Monastery',
    },
  },
  {
    name: 'Nathula Pass',
    key: 'nathula-pass',
    kind: 'landmark',
    parentKey: 'gangtok',
    country: 'India',
    region: 'East',
    domesticOrIntl: 'domestic',
    subcategoryKeys: ['himalayan'],
    profile: {
      description: 'Indo-China border pass — permits mandatory; weather and closures vary.',
      latitude: 27.3869,
      longitude: 88.8308,
      durationMin: 300,
      suitabilityTags: ['permits', 'border', 'adventure'],
      googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Nathula+Pass',
    },
  },

  // ── Assam cities ───────────────────────────────────────────────────
  {
    name: 'Guwahati',
    key: 'guwahati',
    kind: 'city',
    parentKey: 'assam',
    country: 'India',
    region: 'Northeast',
    domesticOrIntl: 'domestic',
    subcategoryKeys: ['wildlife-circuit'],
    profile: {
      description:
        'Gateway city of Assam — Kamakhya, Brahmaputra riverfront, and hub for Meghalaya / Kaziranga circuits.',
      latitude: 26.1445,
      longitude: 91.7362,
      bestTime: 'October–April',
      suitabilityTags: ['gateway', 'temple', 'family'],
      googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Guwahati',
    },
  },
  {
    name: 'Kaziranga',
    key: 'kaziranga',
    kind: 'city',
    parentKey: 'assam',
    country: 'India',
    region: 'Northeast',
    domesticOrIntl: 'domestic',
    subcategoryKeys: ['wildlife-circuit'],
    profile: {
      description: 'UNESCO home of the one-horned rhinoceros — jeep and elephant safari base.',
      latitude: 26.5775,
      longitude: 93.1711,
      bestTime: 'November–April (park open season)',
      suitabilityTags: ['wildlife', 'safari', 'family'],
      googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Kaziranga+National+Park',
    },
  },
  {
    name: 'Tezpur',
    key: 'tezpur',
    kind: 'city',
    parentKey: 'assam',
    country: 'India',
    region: 'Northeast',
    domesticOrIntl: 'domestic',
    profile: {
      description: 'Scenic Assam town on the Brahmaputra — stop en route to Arunachal / Kaziranga.',
      latitude: 26.6338,
      longitude: 92.8,
      suitabilityTags: ['gateway', 'scenic'],
      googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Tezpur',
    },
  },
  {
    name: 'Jorhat',
    key: 'jorhat',
    kind: 'city',
    parentKey: 'assam',
    country: 'India',
    region: 'Northeast',
    domesticOrIntl: 'domestic',
    profile: {
      description: 'Tea-country hub and gateway toward Majuli island.',
      latitude: 26.7509,
      longitude: 94.2037,
      suitabilityTags: ['tea', 'gateway'],
      googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Jorhat',
    },
  },
  {
    name: 'Majuli',
    key: 'majuli',
    kind: 'city',
    parentKey: 'assam',
    country: 'India',
    region: 'Northeast',
    domesticOrIntl: 'domestic',
    subcategoryKeys: ['heritage-circuit'],
    profile: {
      description: 'World’s largest river island — satras, pottery villages, and ferry approaches.',
      latitude: 26.95,
      longitude: 94.15,
      suitabilityTags: ['culture', 'island', 'unique'],
      googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Majuli+Assam',
    },
  },
  {
    name: 'Kamakhya Temple',
    key: 'kamakhya-temple',
    kind: 'landmark',
    parentKey: 'guwahati',
    country: 'India',
    region: 'Northeast',
    domesticOrIntl: 'domestic',
    profile: {
      description: 'Sacred Shakti peeth on Nilachal Hill — key spiritual stop in Guwahati.',
      latitude: 26.1664,
      longitude: 91.7055,
      durationMin: 120,
      suitabilityTags: ['temple', 'pilgrimage'],
      googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Kamakhya+Temple',
    },
  },

  // ── Meghalaya ──────────────────────────────────────────────────────
  {
    name: 'Shillong',
    key: 'shillong',
    kind: 'city',
    parentKey: 'meghalaya',
    country: 'India',
    region: 'Northeast',
    domesticOrIntl: 'domestic',
    subcategoryKeys: ['hill-circuit'],
    profile: {
      description: 'Scotland of the East — falls, cafés, and base for Sohra / Dawki day trips.',
      latitude: 25.5788,
      longitude: 91.8933,
      bestTime: 'September–May',
      suitabilityTags: ['hills', 'family', 'honeymoon'],
      googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Shillong',
    },
  },
  {
    name: 'Sohra (Cherrapunji)',
    key: 'sohra',
    kind: 'city',
    parentKey: 'meghalaya',
    country: 'India',
    region: 'Northeast',
    domesticOrIntl: 'domestic',
    subcategoryKeys: ['hill-circuit'],
    profile: {
      description: 'Legendary rainfall town — canyons, caves, and treks to living root bridges.',
      latitude: 25.2841,
      longitude: 91.721,
      suitabilityTags: ['waterfalls', 'trek', 'monsoon'],
      googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Cherrapunji',
    },
  },
  {
    name: 'Dawki',
    key: 'dawki',
    kind: 'city',
    parentKey: 'meghalaya',
    country: 'India',
    region: 'Northeast',
    domesticOrIntl: 'domestic',
    profile: {
      description: 'Umngot river boat rides and Bangladesh border viewpoint.',
      latitude: 25.1847,
      longitude: 92.0164,
      suitabilityTags: ['boating', 'scenic', 'day-trip'],
      googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Dawki+Meghalaya',
    },
  },
  {
    name: 'Elephant Falls',
    key: 'elephant-falls',
    kind: 'landmark',
    parentKey: 'shillong',
    country: 'India',
    region: 'Northeast',
    domesticOrIntl: 'domestic',
    profile: {
      description: 'Three-tiered fall near Shillong — popular short stop on local sightseeing.',
      latitude: 25.54,
      longitude: 91.822,
      durationMin: 75,
      suitabilityTags: ['waterfall', 'family', 'photo-stop'],
      googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Elephant+Falls+Shillong',
    },
  },
  {
    name: 'Double Decker Living Root Bridge',
    key: 'living-root-bridge-nongriat',
    kind: 'landmark',
    parentKey: 'sohra',
    country: 'India',
    region: 'Northeast',
    domesticOrIntl: 'domestic',
    profile: {
      description: 'Iconic bio-engineered bridge trek via Nongriat — fitness and monsoon caution.',
      latitude: 25.246,
      longitude: 91.665,
      durationMin: 420,
      suitabilityTags: ['trek', 'unique', 'adventure'],
      googleMapsUrl:
        'https://www.google.com/maps/search/?api=1&query=Double+Decker+Living+Root+Bridge',
    },
  },

  // ── Other NE capitals / hubs ───────────────────────────────────────
  {
    name: 'Itanagar',
    key: 'itanagar',
    kind: 'city',
    parentKey: 'arunachal-pradesh',
    country: 'India',
    region: 'Northeast',
    domesticOrIntl: 'domestic',
    subcategoryKeys: ['himalayan'],
    profile: {
      description: 'Capital of Arunachal Pradesh — ILP required for most visitors.',
      latitude: 27.0844,
      longitude: 93.6053,
      suitabilityTags: ['gateway', 'permits'],
      googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Itanagar',
    },
  },
  {
    name: 'Tawang',
    key: 'tawang',
    kind: 'city',
    parentKey: 'arunachal-pradesh',
    country: 'India',
    region: 'Northeast',
    domesticOrIntl: 'domestic',
    subcategoryKeys: ['himalayan'],
    profile: {
      description: 'High monastery town — long drive from Tezpur / Guwahati with permits.',
      latitude: 27.586,
      longitude: 91.859,
      suitabilityTags: ['monastery', 'adventure', 'permits'],
      googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Tawang',
    },
  },
  {
    name: 'Bomdila',
    key: 'bomdila',
    kind: 'city',
    parentKey: 'arunachal-pradesh',
    country: 'India',
    region: 'Northeast',
    domesticOrIntl: 'domestic',
    subcategoryKeys: ['himalayan'],
    profile: {
      description: 'West Kameng hill town — overnight stop on the Tawang axis.',
      latitude: 27.2615,
      longitude: 92.412,
      suitabilityTags: ['hills', 'overnight-stop'],
      googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Bomdila',
    },
  },
  {
    name: 'Dimapur',
    key: 'dimapur',
    kind: 'city',
    parentKey: 'nagaland',
    country: 'India',
    region: 'Northeast',
    domesticOrIntl: 'domestic',
    profile: {
      description: 'Commercial gateway of Nagaland — air/rail access toward Kohima.',
      latitude: 25.9063,
      longitude: 93.7276,
      suitabilityTags: ['gateway'],
      googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Dimapur',
    },
  },
  {
    name: 'Kohima',
    key: 'kohima',
    kind: 'city',
    parentKey: 'nagaland',
    country: 'India',
    region: 'Northeast',
    domesticOrIntl: 'domestic',
    subcategoryKeys: ['heritage-circuit'],
    profile: {
      description: 'Nagaland capital — WWII cemetery and Hornbill festival region.',
      latitude: 25.6751,
      longitude: 94.1086,
      suitabilityTags: ['culture', 'heritage'],
      googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Kohima',
    },
  },
  {
    name: 'Imphal',
    key: 'imphal',
    kind: 'city',
    parentKey: 'manipur',
    country: 'India',
    region: 'Northeast',
    domesticOrIntl: 'domestic',
    profile: {
      description: 'Capital of Manipur — Loktak excursions and cultural heartland.',
      latitude: 24.817,
      longitude: 93.9368,
      suitabilityTags: ['gateway', 'culture'],
      googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Imphal',
    },
  },
  {
    name: 'Aizawl',
    key: 'aizawl',
    kind: 'city',
    parentKey: 'mizoram',
    country: 'India',
    region: 'Northeast',
    domesticOrIntl: 'domestic',
    profile: {
      description: 'Hilltop capital of Mizoram — ILP / inner line considerations apply.',
      latitude: 23.7271,
      longitude: 92.7176,
      suitabilityTags: ['hills', 'gateway'],
      googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Aizawl',
    },
  },
  {
    name: 'Agartala',
    key: 'agartala',
    kind: 'city',
    parentKey: 'tripura',
    country: 'India',
    region: 'Northeast',
    domesticOrIntl: 'domestic',
    profile: {
      description: 'Capital of Tripura — Ujjayanta Palace and soft border culture circuits.',
      latitude: 23.8315,
      longitude: 91.2868,
      suitabilityTags: ['gateway', 'heritage'],
      googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Agartala',
    },
  },
];

/** Re-parent existing transport hubs under correct city/state keys. */
export const NORTHEAST_TRANSPORT_PARENT_OVERRIDES: Record<string, string> = {
  'guwahati-airport': 'guwahati',
  'guwahati-railway': 'guwahati',
  'kamakhya-railway': 'guwahati',
  'shillong-airport': 'shillong',
  'pakyong-airport': 'gangtok',
  'dimapur-airport': 'dimapur',
  'dimapur-railway': 'dimapur',
  'imphal-airport': 'imphal',
  'aizawl-airport': 'aizawl',
  'agartala-airport': 'agartala',
  'agartala-railway': 'agartala',
  'itanagar-airport': 'itanagar',
  'kolkata-airport': 'kolkata',
  'howrah-railway': 'kolkata',
  'kolkata-railway': 'kolkata',
  'new-jalpaiguri-railway': 'siliguri',
  'bagdogra-airport': 'siliguri',
};
