/** Route legs + seasonal tips that seed the Travel OS knowledge layer. */

export type SystemPlaceEdgeSeed = {
  fromKey: string;
  toKey: string;
  mode?: 'drive' | 'flight' | 'rail' | 'walk';
  distanceKm?: number;
  durationMin?: number;
  roadHint?: string;
  stops?: Array<{ name: string; hint?: string }>;
};

export type SystemPlaceKnowledgeSeed = {
  placeKey: string;
  season?: string;
  kind: 'weather' | 'packing' | 'tip' | 'safety' | 'season_rating';
  title?: string;
  body: string;
  meta?: Record<string, unknown>;
};

/** Bidirectional drive times for classic North Bengal circuits. */
export const SYSTEM_PLACE_EDGES: SystemPlaceEdgeSeed[] = [
  {
    fromKey: 'bagdogra-airport',
    toKey: 'darjeeling',
    mode: 'drive',
    distanceKm: 70,
    durationMin: 210,
    roadHint: 'Hill road via NH110 — allow buffer for fog and traffic',
    stops: [{ name: 'Kurseong', hint: 'Optional tea stop / photo pull-off' }],
  },
  {
    fromKey: 'darjeeling',
    toKey: 'bagdogra-airport',
    mode: 'drive',
    distanceKm: 70,
    durationMin: 195,
    roadHint: 'Descend early for evening flights',
  },
  {
    fromKey: 'darjeeling',
    toKey: 'kalimpong',
    mode: 'drive',
    distanceKm: 50,
    durationMin: 165,
    roadHint: 'Via Teesta valley; scenic but winding',
  },
  {
    fromKey: 'kalimpong',
    toKey: 'darjeeling',
    mode: 'drive',
    distanceKm: 50,
    durationMin: 165,
    roadHint: 'Via Teesta valley',
  },
  {
    fromKey: 'bagdogra-airport',
    toKey: 'kalimpong',
    mode: 'drive',
    distanceKm: 75,
    durationMin: 180,
    roadHint: 'Via Sevoke / Teesta',
  },
  {
    fromKey: 'kalimpong',
    toKey: 'bagdogra-airport',
    mode: 'drive',
    distanceKm: 75,
    durationMin: 165,
    roadHint: 'Plan buffer for flight check-in',
  },
  {
    fromKey: 'siliguri',
    toKey: 'darjeeling',
    mode: 'drive',
    distanceKm: 65,
    durationMin: 200,
    roadHint: 'Via NH110; morning starts beat afternoon fog',
    stops: [{ name: 'Kurseong', hint: 'Tea estate photo stop' }],
  },
  {
    fromKey: 'darjeeling',
    toKey: 'siliguri',
    mode: 'drive',
    distanceKm: 65,
    durationMin: 185,
    roadHint: 'Descend before dusk when possible',
  },
  {
    fromKey: 'new-jalpaiguri-railway',
    toKey: 'darjeeling',
    mode: 'drive',
    distanceKm: 68,
    durationMin: 210,
    roadHint: 'Same climb as Siliguri corridor; book Innova / SUV for luggage',
  },
  {
    fromKey: 'darjeeling',
    toKey: 'gangtok',
    mode: 'drive',
    distanceKm: 98,
    durationMin: 270,
    roadHint: 'Via Teesta; permits may apply for Sikkim entry',
  },
  {
    fromKey: 'gangtok',
    toKey: 'darjeeling',
    mode: 'drive',
    distanceKm: 98,
    durationMin: 270,
    roadHint: 'Via Teesta valley',
  },
  {
    fromKey: 'kalimpong',
    toKey: 'gangtok',
    mode: 'drive',
    distanceKm: 75,
    durationMin: 210,
    roadHint: 'Via Teesta / Rangpo checkpost',
  },
  {
    fromKey: 'gangtok',
    toKey: 'kalimpong',
    mode: 'drive',
    distanceKm: 75,
    durationMin: 210,
    roadHint: 'Via Rangpo / Teesta',
  },
  {
    fromKey: 'pakyong-airport',
    toKey: 'gangtok',
    mode: 'drive',
    distanceKm: 35,
    durationMin: 90,
    roadHint: 'Hill road; fog common in evenings',
  },
  {
    fromKey: 'gangtok',
    toKey: 'pakyong-airport',
    mode: 'drive',
    distanceKm: 35,
    durationMin: 85,
    roadHint: 'Leave buffer for flight check-in',
  },
  {
    fromKey: 'gangtok',
    toKey: 'tsomgo-lake',
    mode: 'drive',
    distanceKm: 40,
    durationMin: 120,
    roadHint: 'Permit / weather dependent; cold at lake',
  },
  {
    fromKey: 'tsomgo-lake',
    toKey: 'gangtok',
    mode: 'drive',
    distanceKm: 40,
    durationMin: 110,
  },
  {
    fromKey: 'gangtok',
    toKey: 'rumtek-monastery',
    mode: 'drive',
    distanceKm: 24,
    durationMin: 60,
  },
  {
    fromKey: 'rumtek-monastery',
    toKey: 'gangtok',
    mode: 'drive',
    distanceKm: 24,
    durationMin: 55,
  },
  {
    fromKey: 'gangtok',
    toKey: 'pelling',
    mode: 'drive',
    distanceKm: 115,
    durationMin: 300,
    roadHint: 'Full-day transfer; scenic West Sikkim',
  },
  {
    fromKey: 'pelling',
    toKey: 'gangtok',
    mode: 'drive',
    distanceKm: 115,
    durationMin: 300,
  },
  {
    fromKey: 'guwahati',
    toKey: 'shillong',
    mode: 'drive',
    distanceKm: 100,
    durationMin: 210,
    roadHint: 'Via GS Road; allow traffic buffer',
  },
  {
    fromKey: 'shillong',
    toKey: 'guwahati',
    mode: 'drive',
    distanceKm: 100,
    durationMin: 200,
  },
  {
    fromKey: 'guwahati-airport',
    toKey: 'guwahati',
    mode: 'drive',
    distanceKm: 22,
    durationMin: 60,
  },
  {
    fromKey: 'guwahati',
    toKey: 'guwahati-airport',
    mode: 'drive',
    distanceKm: 22,
    durationMin: 55,
  },
  {
    fromKey: 'shillong',
    toKey: 'sohra',
    mode: 'drive',
    distanceKm: 55,
    durationMin: 120,
  },
  {
    fromKey: 'sohra',
    toKey: 'shillong',
    mode: 'drive',
    distanceKm: 55,
    durationMin: 115,
  },
  {
    fromKey: 'shillong',
    toKey: 'dawki',
    mode: 'drive',
    distanceKm: 80,
    durationMin: 180,
  },
  {
    fromKey: 'dawki',
    toKey: 'shillong',
    mode: 'drive',
    distanceKm: 80,
    durationMin: 170,
  },
  {
    fromKey: 'guwahati',
    toKey: 'kaziranga',
    mode: 'drive',
    distanceKm: 220,
    durationMin: 300,
    roadHint: 'Long plains drive; early start recommended',
  },
  {
    fromKey: 'kaziranga',
    toKey: 'guwahati',
    mode: 'drive',
    distanceKm: 220,
    durationMin: 290,
  },
  {
    fromKey: 'darjeeling',
    toKey: 'tiger-hill',
    mode: 'drive',
    distanceKm: 14,
    durationMin: 45,
    roadHint: 'Pre-dawn convoy; cold at viewpoint',
  },
  {
    fromKey: 'tiger-hill',
    toKey: 'darjeeling',
    mode: 'drive',
    distanceKm: 14,
    durationMin: 40,
  },
];

export const SYSTEM_PLACE_KNOWLEDGE: SystemPlaceKnowledgeSeed[] = [
  {
    placeKey: 'darjeeling',
    season: 'winter',
    kind: 'weather',
    title: 'Winter in Darjeeling',
    body: 'Crisp mornings around 4–10°C in Dec–Jan; clear sunrise windows are more common after cold nights. Pack layers for Tiger Hill.',
  },
  {
    placeKey: 'darjeeling',
    season: 'all',
    kind: 'packing',
    title: 'What to pack',
    body: 'Warm jacket, walking shoes with grip, sunglasses, and a light rain shell. Evenings on Mall Road can feel colder than town midday.',
  },
  {
    placeKey: 'darjeeling',
    season: 'all',
    kind: 'tip',
    title: 'Altitude & energy',
    body: 'Tiger Hill starts before dawn — optional for elders. Build a slow breakfast after sunrise before town walks.',
  },
  {
    placeKey: 'darjeeling',
    season: 'all',
    kind: 'tip',
    title: 'Toy train windows',
    body: 'Book toy-train seats ahead in peak season; Batasia Loop pairs well with a short train hop or drive-by stop.',
  },
  {
    placeKey: 'kalimpong',
    season: 'all',
    kind: 'weather',
    title: 'Kalimpong climate',
    body: 'Slightly milder than Darjeeling with open skyline views from Delo. Mornings can still be chilly in winter.',
  },
  {
    placeKey: 'kalimpong',
    season: 'all',
    kind: 'packing',
    title: 'Kalimpong packing',
    body: 'Comfortable walking shoes for Delo lawns, a light fleece, and sun protection for open viewpoints.',
  },
  {
    placeKey: 'kalimpong',
    season: 'all',
    kind: 'tip',
    title: 'Nurseries & pace',
    body: 'Leave half a day unhurried for orchid nurseries and Durpin — Kalimpong rewards a slower evening than Darjeeling.',
  },
  {
    placeKey: 'gangtok',
    season: 'all',
    kind: 'weather',
    title: 'Gangtok weather',
    body: 'Cool evenings year-round; monsoon (Jun–Sep) brings road delays to North Sikkim. Carry a compact rain shell.',
  },
  {
    placeKey: 'gangtok',
    season: 'all',
    kind: 'packing',
    title: 'Gangtok packing',
    body: 'Warm layer for evenings, comfortable shoes for MG Marg, and documents for Sikkim permits if heading beyond town.',
  },
  {
    placeKey: 'siliguri',
    season: 'all',
    kind: 'tip',
    title: 'Gateway timing',
    body: 'Arrive Bagdogra / NJP by midday when possible — hill climbs after dark are slower and less scenic for guests.',
  },
  {
    placeKey: 'kurseong',
    season: 'all',
    kind: 'tip',
    title: 'Tea-stop rhythm',
    body: 'A 20–30 minute estate pull-off on the Bagdogra climb breaks travel fatigue for elders and kids.',
  },
  {
    placeKey: 'north-bengal',
    season: 'all',
    kind: 'tip',
    title: 'Hill road buffer',
    body: 'Always keep flex time on Bagdogra transfers — fog and traffic on the climb are normal in peak season.',
  },
  {
    placeKey: 'north-bengal',
    season: 'all',
    kind: 'packing',
    title: 'Hills circuit packing',
    body: 'Layers for 5–18°C swings, grip shoes, small daypack for sunrise, personal altitude meds if sensitive.',
  },
  {
    placeKey: 'north-bengal',
    season: 'winter',
    kind: 'weather',
    title: 'Peak clarity season',
    body: 'Dec–Feb often brings the clearest Kanchenjunga views after cold nights — confirm dawn transfers the evening before.',
  },
  {
    placeKey: 'guwahati',
    season: 'all',
    kind: 'tip',
    title: 'NE hub pacing',
    body: 'Use Guwahati as a soft landing night before Shillong or Kaziranga — same-day long drives fatigue first-time NE travellers.',
  },
  {
    placeKey: 'guwahati',
    season: 'all',
    kind: 'weather',
    title: 'Assam plains weather',
    body: 'Warm and humid Oct–Apr days; monsoon (Jun–Sep) can disrupt hill roads into Meghalaya.',
  },
  {
    placeKey: 'shillong',
    season: 'all',
    kind: 'packing',
    title: 'Meghalaya packing',
    body: 'Waterproof layer year-round, grip shoes for falls, light fleece for evenings even in summer.',
  },
  {
    placeKey: 'shillong',
    season: 'all',
    kind: 'tip',
    title: 'Sohra vs Dawki days',
    body: 'Keep Sohra and Dawki on separate days when possible — both are full scenic days from Shillong.',
  },
  {
    placeKey: 'kaziranga',
    season: 'all',
    kind: 'tip',
    title: 'Safari booking',
    body: 'Book jeep/elephant safaris in advance in peak season; early slots are quieter and better for rhino sightings.',
  },
  {
    placeKey: 'tawang',
    season: 'all',
    kind: 'safety',
    title: 'Permits & altitude',
    body: 'ILP / protected-area permits required. Pace acclimatization; nights are cold year-round.',
  },
  {
    placeKey: 'sikkim',
    season: 'all',
    kind: 'tip',
    title: 'Sikkim permits',
    body: 'Domestic visitors usually get entry permits at Rangpo / Melli; Nathula and North Sikkim need additional permits and closed days.',
  },
];
